# Generated by Django 6.0.6 on 2026-07-04 21:03

import annotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationimage',
            name='file',
            field=models.ImageField(upload_to=annotation.models.annotation_upload_to),
        ),
    ]
