# Generated by Django 6.0.6 on 2026-07-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0002_alter_annotationimage_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='label_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='polygon',
            name='label_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
